# Makefile for `wget' utility
# Copyright (C) 1995, 1996, 1997 Free Software Foundation, Inc.

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

RM = del

all: wget.hlp

# You probably need makeinfo utility
# wget it from URL:http://www.sunsite.auc.dk/wget/makeinfo.zip

.IGNORE:
wget.hlp: wget.texi
        makeinfo --no-validate --no-warn --force \
--hpj wget.hpj --output wget.rtf wget.texi
        hcrtf -xn wget.hpj

clean:
        $(RM) *.bak
        $(RM) *.hpj
        $(RM) *.rtf
        $(RM) *.ph

distclean: clean
        $(RM) wget.hlp
	$(RM) Makefile

realclean: distclean

